### ISSUE TITLE
Unsuccesful development install

### ISSUE THREAD

**Issue by ldania** [RoboStack/jupyter-ros#141]
Actions:

```
$ pip3 install "git+https://github.com/Robostack/jupyter-ros"
```

Environment:
Ubuntu 22.0, Ros2 Humble

Expected Results:
```
Successful install 
```

Result:
`````````
Building wheels for collected packages: jupyros
  Building wheel for jupyros (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for jupyros (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      yarn install v1.21.1
      [1/4] Resolving packages...
      [2/4] Fetching packages...
      [3/4] Linking dependencies...
      warning "@jupyter-widgets/base > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
      [4/4] Building fresh packages...
      $ webpack
      node:internal/crypto/hash:71
        this[kHandle] = new _Hash(algorithm, xofLen);
                        ^
      
      Error: error:0308010C:digital envelope routines::unsupported
          at new Hash (node:internal/crypto/hash:71:19)
          at Object.createHash (node:crypto:133:10)
          at BulkUpdateDecorator.hashFactory (/tmp/pip-req-build-2e5z22x1/js/node_modules/webpack/lib/util/createHash.js:144:18)
          at BulkUpdateDecorator.update (/tmp/pip-req-build-2e5z22x1/js/node_modules/webpack/lib/util/createHash.js:46:50)
          at OriginalSource.updateHash (/tmp/pip-req-build-2e5z22x1/js/node_modules/webpack/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
          at NormalModule._initBuildHash (/tmp/pip-req-build-2e5z22x1/js/node_modules/webpack/lib/NormalModule.js:753:17)
          at handleParseResult (/tmp/pip-req-build-2e5z22x1/js/node_modules/webpack/lib/NormalModule.js:817:10)
          at /tmp/pip-req-build-2e5z22x1/js/node_modules/webpack/lib/NormalModule.js:908:4
          at processResult (/tmp/pip-req-build-2e5z22x1/js/node_modules/webpack/lib/NormalModule.js:640:11)
          at /tmp/pip-req-build-2e5z22x1/js/node_modules/webpack/lib/NormalModule.js:692:5 {
        opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
        library: 'digital envelope routines',
        reason: 'unsupported',
        code: 'ERR_OSSL_EVP_UNSUPPORTED'
      }
      
      Node.js v18.10.0
      error Command failed with exit code 1.
      info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
      Traceback (most recent call last):
        File "/home/dobots/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/dobots/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/dobots/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-27q3pzbo/overlay/lib/python3.9/site-packages/jupyter_packaging/build_api.py", line 22, in build_wheel
          builder()
        File "/tmp/pip-build-env-27q3pzbo/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 231, in builder
          run(npm_cmd + ["install"], cwd=node_package)
        File "/tmp/pip-build-env-27q3pzbo/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 297, in run
          return subprocess.check_call(cmd, **kwargs)
        File "/home/dobots/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/tmp/pip-build-env-27q3pzbo/overlay/bin/jlpm', 'install']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jupyros
Failed to build jupyros
ERROR: Could not build wheels for jupyros, which is required to install pyproject.toml-based projects
`

**Comment by ldania** [comment]
Issue was caused by a separate library causing conflicting dependency. "rosboard" caused the issue. 
But did not find the core issue.

**Comment by hbcarlos** [comment]
Hi @ldania! Thanks for opening the issue.
I have seen this issue in upstream packages (for example, when building JupyterLab). I believe this is not coming from jupyros but from the upstream packages.
I can see you are using `nodejs==18`. Try using `nodejs=14`. You may get around it for now.
