### ISSUE TITLE
jupyros | error adding extension (enabled: True): name 'Unicode' is not defined

### ISSUE THREAD

**Issue by mirkosertic** [RoboStack/jupyter-ros#154]
Hi@all,

i am getting the following error after installing jupyros with micromamba:

```[W 2023-05-19 12:46:02.520 ServerApp] jupyros | error adding extension (enabled: True): name 'Unicode' is not defined
    Traceback (most recent call last):
      File "/home/mirkosertic/micromamba/envs/ros_jupyter/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/home/mirkosertic/micromamba/envs/ros_jupyter/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/home/mirkosertic/micromamba/envs/ros_jupyter/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 192, in _load_metadata
        self.module, self.metadata = get_metadata(name, logger=self.log)
      File "/home/mirkosertic/micromamba/envs/ros_jupyter/lib/python3.9/site-packages/jupyter_server/extension/utils.py", line 71, in get_metadata
        module = importlib.import_module(package_name)
      File "/home/mirkosertic/micromamba/envs/ros_jupyter/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/home/mirkosertic/micromamba/envs/ros_jupyter/lib/python3.9/site-packages/jupyros/__init__.py", line 16, in <module>
        from .ros3d import *
      File "/home/mirkosertic/micromamba/envs/ros_jupyter/lib/python3.9/site-packages/jupyros/ros3d.py", line 60, in <module>
        class ROSConnection(widgets.Widget):
      File "/home/mirkosertic/micromamba/envs/ros_jupyter/lib/python3.9/site-packages/jupyros/ros3d.py", line 75, in ROSConnection
        url = Unicode(os.environ.get("JUPYROS_WEBSOCKET_URL", "ws://{hostname}:9090")).tag(sync=True)
    NameError: name 'Unicode' is not defined
```

any ideas what I am missing? I'd really like to give it a try, but unfortunately there is this issue in my environment, and I really do not have a glue about how to proceed.

For completeness, here is the command I used to create a fresh environment:

`micromamba create -n ros_jupyter python=3.9 jupyter-ros -c robostack -c conda-forge --no-channel-priority --override-channels`

**Comment by mirkosertic** [comment]
conda seems to work just fine, installation with micromamba is causing this issue.
