### ISSUE TITLE
import jupyros is failing

### ISSUE THREAD

**Issue by jlmeunier** [RoboStack/jupyter-ros#155]
Hi there!

Several names are unknown in the code. 
It started by Unicode in file `jupyros/ros3d.py`
=> I explicitly import it by a `from traitlets import Unicode`
But then, I'm getting a:
```
>>> import jupyros
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/meunier/miniforge3/envs/ros_env2/lib/python3.9/site-packages/jupyros/__init__.py", line 16, in <module>
    from .ros3d import *
  File "/home/meunier/miniforge3/envs/ros_env2/lib/python3.9/site-packages/jupyros/ros3d.py", line 78, in <module>
    class TFClient(widgets.Widget):
  File "/home/meunier/miniforge3/envs/ros_env2/lib/python3.9/site-packages/jupyros/ros3d.py", line 95, in TFClient
    ros = Instance(ROSConnection).tag(**sync_widget)
NameError: name 'Instance' is not defined
```

I've done the standard installation of **Robotstack**, for ROS **Noetic**, followed by: `mamba install jupyter-ros -c robostack` 
On a **x86_64** macchine running **Ubuntu 20.04.6 LTS**

Some version info:
```
jupyter-ros               0.5.0              pyhd8ed1ab_0    robostack
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_core              5.5.0            py39hf3d152e_0    conda-forge
jupyter_events            0.9.0              pyhd8ed1ab_0    conda-forge
jupyter_server            2.10.1             pyhd8ed1ab_0    conda-forge
jupyter_server_fileid     0.9.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyter_server_ydoc       0.8.0              pyhd8ed1ab_0    conda-forge
jupyter_ydoc              0.2.4              pyhd8ed1ab_0    conda-forge
jupyterlab                3.6.6              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.1             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.9              pyhd8ed1ab_0    conda-forge
```

Thanks for any help,
JL

**Comment by ihuicatl** [comment]
Hi @jlmeunier !

This issue was fixed with https://github.com/RoboStack/jupyter-ros/pull/145

Please try with the new release v0.7.0

```
pip install jupyros==0.7.0
```
