### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'register_magic_function'

### ISSUE THREAD

**Issue by liampaull** [RoboStack/jupyter-ros#37]
commands to reproduce:

   pip3 install jupyros
   jupyter nbextension enable --py --sys-prefix jupyros

on version 0.2.0 gave the output: 
```
The rospy package is not found in your $PYTHONPATH. Subscribe and publish are not going to work.
Do you need to activate your ROS environment?
Enabling notebook extension jupyter-ros/extension...
      - Validating: OK
```
now in version 0.2.1 gives the error:
```
The rospy package is not found in your $PYTHONPATH. Subscribe and publish are not going to work.
Do you need to activate your ROS environment?
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/usr/local/lib/python3.6/dist-packages/jupyros/__init__.py", line 5, in <module>
    from .ipy import *
  File "/usr/local/lib/python3.6/dist-packages/jupyros/ipy.py", line 9, in <module>
    @register_cell_magic
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/magic.py", line 238, in magic_deco
    ip.register_magic_function(func, magic_kind, name)
AttributeError: 'NoneType' object has no attribute 'register_magic_function'
```

**Comment by wolfv** [comment]
thanks for the bug report, i am working on it. There should be a fix for this by tonight.

**Comment by wolfv** [comment]
I've released a new version -- can you check it out?

**Comment by liampaull** [comment]
seems good now thanks!
