### ISSUE TITLE
Errno 'jupyter-labextension' not found

### ISSUE THREAD

**Issue by Airyzf** [RoboStack/jupyter-ros#4]
I got error when I ran the code
"jupyter labextension install jupyter-ros "

Error executing Jupyter command 'labextension': [Errno 'jupyter-labextension' not found] 2

**Comment by wolfv** [comment]
can you install jupyter lab first? `pip install jupyterlab`

**Comment by Airyzf** [comment]
> can you install jupyter lab first? `pip install jupyterlab`

thanks, I got it.

**Comment by Airyzf** [comment]
> can you install jupyter lab first? `pip install jupyterlab`

oh no, I got another error

 D:\python\jupyter-ros-master>jupyter nbextension install --py --symlink --sys-prefix jupyros
The rospy package is not found in your $PYTHONPATH. Subscribe and publish are not going to work.
Do you need to activate your ROS environment?
Installing d:\python\jupyter-ros-master\jupyros\static -> jupyter-ros
Symlinking: D:\Anaconda3\envs\tf2test\share\jupyter\nbextensions\jupyter-ros -> d:\python\jupyter-ros-master\jupyros\static
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tf2test\Scripts\jupyter-nbextension-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Anaconda3\envs\tf2test\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "D:\Anaconda3\envs\tf2test\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\Anaconda3\envs\tf2test\lib\site-packages\notebook\nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "D:\Anaconda3\envs\tf2test\lib\site-packages\jupyter_core\application.py", line 255, in start
    self.subapp.start()
  File "D:\Anaconda3\envs\tf2test\lib\site-packages\notebook\nbextensions.py", line 716, in start
    self.install_extensions()
  File "D:\Anaconda3\envs\tf2test\lib\site-packages\notebook\nbextensions.py", line 695, in install_extensions
    **kwargs
  File "D:\Anaconda3\envs\tf2test\lib\site-packages\notebook\nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "D:\Anaconda3\envs\tf2test\lib\site-packages\notebook\nbextensions.py", line 184, in install_nbextension
    os.symlink(path, full_dest)
OSError: symbolic link privilege not held

**Comment by spdaly** [comment]
Installing extensions with the jupyter labextension install command is now deprecated and will be removed in a future major version of JupyterLab.
