### ISSUE TITLE
installation issue as root inside dockerfile

### ISSUE THREAD

**Issue by ljburtz** [RoboStack/jupyter-ros#66]
Hello and thank you for this great project!
I'm trying to package it in a ROS Docker image

I have an error when installing (following the .README instructions)

Would anybody here have an idea of what might be the problem?
Thank you so much.

```sh
Step 25/41 : RUN mkdir -p ~/utilities/ && cd ~/utilities/ && git clone https://github.com/RoboStack/jupyter-ros.git && cd ~/utilities/jupyter-ros && pip3 install -e .
 ---> Running in a9e29d0dc56b
Cloning into 'jupyter-ros'...
Obtaining file:///root/utilities/jupyter-ros
    Complete output from command python setup.py egg_info:
    setup.py entered
    $PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    running egg_info
    running jsdeps
    6.14.6
    6.14.6
    Installing build dependencies with npm.  This may take a while...
    
    > uglifyjs-webpack-plugin@0.4.6 postinstall /root/utilities/jupyter-ros/js/node_modules/uglifyjs-webpack-plugin
    > node lib/post_install.js
    
    npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
    npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
    npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
    npm WARN lifecycle jupyter-ros@0.3.0~prepublish: cannot run in wd jupyter-ros@0.3.0 webpack (wd=/root/utilities/jupyter-ros/js)
    npm WARN jupyter-ros@0.3.0 No license field.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    
    added 432 packages from 380 contributors and audited 501 packages in 5.414s
    found 113 vulnerabilities (109 low, 2 moderate, 2 high)
      run `npm audit fix` to fix them, or `npm audit` for details
    rebuilding js and css failed
    missing files: ['/root/utilities/jupyter-ros/jupyros/static/extension.js', '/root/utilities/jupyter-ros/jupyros/static/index.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/utilities/jupyter-ros/setup.py", line 180, in <module>
        setup(**setup_args)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/utilities/jupyter-ros/setup.py", line 45, in run
        raise e
      File "/root/utilities/jupyter-ros/setup.py", line 38, in run
        self.distribution.run_command('jsdeps')
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/utilities/jupyter-ros/setup.py", line 118, in run
        raise ValueError(msg)
    ValueError: Missing file: /root/utilities/jupyter-ros/jupyros/static/extension.js
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /root/utilities/jupyter-ros/

```

**Comment by Tiryoh** [comment]
I’ve created a project using Docker. I hope this helps.

https://github.com/Tiryoh/mini-pupper-jupyter-notebooks/blob/main/docker/conda-jupyter-ros/Dockerfile
